import { iCoupon } from "@/types/types";

export const couponsData: iCoupon[] = [
  {
    id: "1",
    code: "SAVE10",
    startDate: "2025-01-01",
    endDate: "2025-01-31",
    customerDiscountType: "Percentage",
    withFreeShipping: "Yes",
    ExceptionToDiscountedProducts: "No",
    MinimumPurchase: "$50",
    NumberOfTimesUsedForAll: "100",
    NumberOfUsesPerCustomer: "1",
    PersonsName: "John Doe",
    CommissionTypeForMarketer: "Flat",
    CommissionRate: "5",
    AdditionalInformation: "Valid for all users",
    PaymentMethodsIncludedInTheCoupon: "Credit Card, PayPal",
    ClientEmailDomain: "example.com",
    ExcludedCustomerGroups: "VIP",
    ExcludedProducts: "Gift Cards",
    status: 1,
  },
  {
    id: "2",
    code: "FREESHIP",
    startDate: "2025-02-01",
    endDate: "2025-02-15",
    customerDiscountType: "Flat",
    withFreeShipping: "Yes",
    ExceptionToDiscountedProducts: "Yes",
    MinimumPurchase: "$30",
    NumberOfTimesUsedForAll: "50",
    NumberOfUsesPerCustomer: "2",
    PersonsName: "Jane Smith",
    CommissionTypeForMarketer: "Percentage",
    CommissionRate: "10",
    AdditionalInformation: "Free shipping only",
    PaymentMethodsIncludedInTheCoupon: "Debit Card, PayPal",
    ClientEmailDomain: "mydomain.com",
    ExcludedCustomerGroups: "Retailers",
    ExcludedProducts: "Electronics",
    status: 0,
  },
  {
    id: "3",
    code: "HOLIDAY20",
    startDate: "2025-12-01",
    endDate: "2025-12-31",
    customerDiscountType: "Percentage",
    withFreeShipping: "No",
    ExceptionToDiscountedProducts: "No",
    MinimumPurchase: "$100",
    NumberOfTimesUsedForAll: "200",
    NumberOfUsesPerCustomer: "3",
    PersonsName: "Alice Johnson",
    CommissionTypeForMarketer: "Flat",
    CommissionRate: "15",
    AdditionalInformation: "Holiday special discount",
    PaymentMethodsIncludedInTheCoupon: "All",
    ClientEmailDomain: "holiday.com",
    ExcludedCustomerGroups: "Employees",
    ExcludedProducts: "Luxury Items",
    status: 1,
  },
  {
    id: "4",
    code: "BLACKFRIDAY",
    startDate: "2025-11-25",
    endDate: "2025-11-30",
    customerDiscountType: "Flat",
    withFreeShipping: "Yes",
    ExceptionToDiscountedProducts: "Yes",
    MinimumPurchase: "$75",
    NumberOfTimesUsedForAll: "300",
    NumberOfUsesPerCustomer: "5",
    PersonsName: "Michael Brown",
    CommissionTypeForMarketer: "Percentage",
    CommissionRate: "20",
    AdditionalInformation: "Black Friday deal",
    PaymentMethodsIncludedInTheCoupon: "Credit Card",
    ClientEmailDomain: "shopnow.com",
    ExcludedCustomerGroups: "None",
    ExcludedProducts: "Furniture",
    status: 1,
  },
  {
    id: "5",
    code: "SUMMER2025",
    startDate: "2025-06-01",
    endDate: "2025-08-31",
    customerDiscountType: "Percentage",
    withFreeShipping: "No",
    ExceptionToDiscountedProducts: "No",
    MinimumPurchase: "$60",
    NumberOfTimesUsedForAll: "150",
    NumberOfUsesPerCustomer: "2",
    PersonsName: "Emily Davis",
    CommissionTypeForMarketer: "Flat",
    CommissionRate: "25",
    AdditionalInformation: "Summer sale discount",
    PaymentMethodsIncludedInTheCoupon: "Credit Card, Bank Transfer",
    ClientEmailDomain: "summerdeals.com",
    ExcludedCustomerGroups: "Wholesale Buyers",
    ExcludedProducts: "Home Appliances",
    status: 0,
  },
];
