import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Salla Task",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1.0",
  icons: {
    icon: "https://cdn.salla.network/images/logo/logo-light-wide.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <div className="flex">
        <Sidebar />
        <div className="flex-1" style={{ maxWidth: "calc(100% - 60px)" }}>
          <Navbar />
          {children}
        </div>
      </div>
      </body>
    </html>
  );
}
